kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: rust:latest
    volumes:
      - name: rust-cache
        path: /cache
    commands:
      - cargo build --release --verbose --manifest-path something/Cargo.toml
    environment:
      RUSTUP_HOME: /cache/rustup
      CARGO_HOME: /cache/cargo

  - name: test
    image: rust:latest
    volumes:
      - name: rust-cache
        path: /cache
    commands:
      - cargo test --verbose --manifest-path something/Cargo.toml
    environment:
      RUSTUP_HOME: /cache/rustup
      CARGO_HOME: /cache/cargo

  - name: build-test-hil
    pull: if-not-exists
    image: jacobrosenthal/drone-runner-rust-teleprobe
    volumes:
      - name: rust-cache
        path: /cache
    commands:
      - cargo batch --- build --release --manifest-path tests/nrf52840/Cargo.toml --target thumbv7em-none-eabi --out-dir out/tests/nrf52840-dk
      - teleprobe client --token $TELEPROBE_TOKEN --host $TELEPROBE_HOST run -r out/tests
    environment:
      RUSTUP_HOME: /cache/rustup
      CARGO_HOME: /cache/cargo
      TELEPROBE_TOKEN:
        from_secret: TELEPROBE_TOKEN
      TELEPROBE_HOST:
        from_secret: TELEPROBE_HOST

volumes:
  - name: rust-cache
    host:
      path: /cache
