kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: rust:latest
    commands:
      - cargo build --release --verbose --manifest-path something/Cargo.toml

  - name: test
    image: rust:latest
    commands:
      - cargo test --verbose --manifest-path something/Cargo.toml

  - name: build-test-hil
    pull: if-not-exists
    image: jacobrosenthal/drone-runner-rust-teleprobe
    commands:
      - cargo batch --- build --release --manifest-path tests/nrf52840/Cargo.toml --target thumbv7em-none-eabi --out-dir out/tests/nrf52840-dk
      - teleprobe client --token ${TELEPROBE_TOKEN} --host '${TELEPROBE_HOST}' run -r out/tests
    environment:
      TELEPROBE_HOST:
        from_secret: TELEPROBE_HOST
      TELEPROBE_TOKEN:
        from_secret: TELEPROBE_TOKEN
