name: Build and Send Binary

on: [push]

jobs:
  build-and-send:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --manifest-path tests/nrf52840/Cargo.toml --target thumbv7em-none-eabi --bin timer

      - name: test timer
        env:
          TELEPROBE_HOST: ${{ secrets.TELEPROBE_HOST }}
          TELEPROBE_TOKEN: ${{ secrets.TELEPROBE_TOKEN }}
        run: |
          response=$(curl -s -X POST "${TELEPROBE_HOST}/targets/nrf52840-dk/run?timeout=60" \
                          -H "Authorization: Bearer ${TELEPROBE_TOKEN}" \
                          -H "Content-Type: application/octet-stream" \
                          --data-binary "@tests/nrf52840/target/thumbv7em-none-eabi/release/timer" \
                          -w "\n%{http_code}")
          echo "$response"
          http_status=$(echo "$response" | tail -n1)
          [ "$http_status" -ge 200 ] && [ "$http_status" -lt 300 ] && echo "Test succeeded" || { echo "Test failed"; exit 1; }

      - name: test timer2
        env:
          TELEPROBE_HOST: ${{ secrets.TELEPROBE_HOST }}
          TELEPROBE_TOKEN: ${{ secrets.TELEPROBE_TOKEN }}
        run: |
          response=$(curl -s -X POST "${TELEPROBE_HOST}/targets/nrf52840-dk/run?timeout=60" \
                          -H "Authorization: Bearer ${TELEPROBE_TOKEN}" \
                          -H "Content-Type: application/octet-stream" \
                          --data-binary "@tests/nrf52840/target/thumbv7em-none-eabi/release/timer2" \
                          -w "\n%{http_code}")
          echo "$response"
          http_status=$(echo "$response" | tail -n1)
          [ "$http_status" -ge 200 ] && [ "$http_status" -lt 300 ] && echo "Test succeeded" || { echo "Test failed"; exit 1; }
