name: CI

on: [pull_request]

jobs:
  hil:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.actor == 'jacobrosenthal'

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@v1
        with:
          target: thumbv7em-none-eabi
          toolchain: 1.75
          components: rust-src, rustfmt, llvm-tools

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            tests/nrf52840/target/
          key: ${{ runner.os }}-cargo-tests-nrf52840-${{ hashFiles('tests/nrf52840/Cargo.lock') }}

      - name: install curl
        run: sudo apt-get install curl

      - name: install cargo-batch
        run: curl -L -o /usr/local/bin/cargo-batch https://github.com/embassy-rs/cargo-batch/releases/download/batch-0.3.0/cargo-batch && chmod +x /usr/local/bin/cargo-batch

      - name: build HIL
        run: cargo batch --- build --release --manifest-path tests/nrf52840/Cargo.toml --target thumbv7em-none-eabi --out-dir out/tests

      - name: install teleprobe
        run: curl -L -o /usr/local/bin/teleprobe https://github.com/jacobrosenthal/teleprobe/releases/download/v0.1.0-static/teleprobe-v0.1.0-static-linux-x64 && chmod +x /usr/local/bin/teleprobe

      - name: test HIL
        run: teleprobe client --token ${{ secrets.TELEPROBE_TOKEN }} --host ${{ secrets.TELEPROBE_HOST }} run -r out/tests
