name: SIZE

on:
  pull_request:
    types: [closed]

permissions:
  contents: write # Git notes

jobs:
  post-merge-job:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.rustup/
          key: ${{ runner.os }}-rust-toolchain-${{ hashFiles('rust-toolchain.toml') }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-something-nrf52840-${{ hashFiles('something-nrf52840/Cargo.lock') }}

      - name: build
        run: cargo build --manifest-path something-nrf52840/Cargo.toml --target thumbv7em-none-eabi

      - name: install binutils
        run: cargo install cargo-binutils

      - name: cargo size and set output
        id: cargo_size
        run: |
          echo "size<<EOF" >> $GITHUB_OUTPUT
          cargo size -q --target thumbv7em-none-eabi --release >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        working-directory: something-nrf52840
        continue-on-error: true

      - name: Add analysis results to Git notes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin refs/notes/*:refs/notes/*
          git notes --ref cargo-size-berkley add -m "${{ steps.cargo_size.outputs.size }}" ${{ github.event.pull_request.merge_commit_sha }}
          git push origin refs/notes/*
        continue-on-error: true
